#!/bin/bash
# Database Backup Script
# Generated by setup-backups.ts

set -e

BACKUP_DIR="./backups"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BACKUP_FILE="full-${TIMESTAMP}.sql"

# Create backup directory if it doesn't exist
mkdir -p $BACKUP_DIR

# Full backup
echo "Starting full backup..."
pg_dump $DATABASE_URL | gzip > "$BACKUP_DIR/$BACKUP_FILE.gz"

# Upload to S3 if configured
if [ ! -z "$AWS_S3_BACKUP_BUCKET" ]; then
  echo "Uploading to S3..."
  aws s3 cp "$BACKUP_DIR/$BACKUP_FILE.gz" "s3://$AWS_S3_BACKUP_BUCKET/database-backups/$BACKUP_FILE.gz"
fi

# Cleanup old backups (keep last 4 weeks)
find $BACKUP_DIR -name "full-*.sql.gz" -mtime +28 -delete

echo "Backup completed: $BACKUP_FILE.gz"