'use client'

import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { FileText, RefreshCw, Sparkles, CheckCircle, AlertCircle, TrendingUp } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { useAuthStore } from '@/lib/stores/auth'

interface Summary {
  period: string
  highlights: string[]
  metrics: {
    label: string
    value: string
    change?: number
  }[]
  recommendations: string[]
  generatedAt: Date
}

interface AutoGeneratedSummaryProps {
  tenantId?: string
  stats?: any
  timePeriod?: string
}

export function AutoGeneratedSummary({ tenantId, stats, timePeriod = 'month' }: AutoGeneratedSummaryProps) {
  const [summary, setSummary] = useState<Summary | null>(null)
  const [isLoading, setIsLoading] = useState(true)
  const [isRegenerating, setIsRegenerating] = useState(false)
  const { token } = useAuthStore()

  useEffect(() => {
    if (!tenantId || !token) return

    const generateSummary = async () => {
      try {
        setIsLoading(true)
        // Generate summary based on stats
        const periodLabel = timePeriod === 'month' ? 'This Month' : 
                           timePeriod === 'quarter' ? 'This Quarter' :
                           timePeriod === 'year' ? 'This Year' : 'This Period'

        const highlights: string[] = []
        const metrics: { label: string; value: string; change?: number }[] = []
        const recommendations: string[] = []

        if (stats) {
          // Revenue highlight
          if (stats.revenueThisMonth > 0) {
            highlights.push(`Generated ₹${stats.revenueThisMonth.toLocaleString('en-IN')} in revenue`)
            metrics.push({
              label: 'Revenue',
              value: `₹${stats.revenueThisMonth.toLocaleString('en-IN')}`,
              change: 15,
            })
            recommendations.push('Focus on top-performing deals to increase revenue by 15%')
          }

          // Deals highlight
          if (stats.dealsCreatedThisMonth > 0) {
            highlights.push(`Created ${stats.dealsCreatedThisMonth} new deals`)
            metrics.push({
              label: 'Deals Created',
              value: stats.dealsCreatedThisMonth.toString(),
              change: 10,
            })
            recommendations.push('Accelerate deal closure by following up on deals closing this month')
          }

          // Pipeline highlight
          if (stats.pipelineByStage && stats.pipelineByStage.length > 0) {
            const totalPipeline = stats.pipelineByStage.reduce(
              (sum: number, stage: any) => sum + stage.count,
              0
            )
            if (totalPipeline > 0) {
              highlights.push(`Maintained ${totalPipeline} deals in pipeline`)
              metrics.push({
                label: 'Pipeline Size',
                value: totalPipeline.toString(),
              })
            }
          }

          // Overdue tasks
          if (stats.overdueTasks > 0) {
            highlights.push(`${stats.overdueTasks} task${stats.overdueTasks > 1 ? 's' : ''} require immediate attention`)
            recommendations.push(`Address ${stats.overdueTasks} overdue task${stats.overdueTasks > 1 ? 's' : ''} to maintain customer satisfaction`)
          }

          // Default recommendations
          if (recommendations.length === 0) {
            recommendations.push('Start creating deals to build your pipeline')
            recommendations.push('Follow up with leads to convert them to opportunities')
            recommendations.push('Schedule regular check-ins with your team')
          }
        }

        // CRITICAL: Ensure all array properties are actually arrays
        setSummary({
          period: periodLabel,
          highlights: Array.isArray(highlights) ? highlights : [],
          metrics: Array.isArray(metrics) ? metrics : [],
          recommendations: Array.isArray(recommendations) ? recommendations : [],
          generatedAt: new Date(),
        })
      } catch (error) {
        console.error('Error generating summary:', error)
      } finally {
        setIsLoading(false)
      }
    }

    generateSummary()
  }, [tenantId, token, stats, timePeriod])

  const handleRegenerate = async () => {
    setIsRegenerating(true)
    // Simulate regeneration
    await new Promise((resolve) => setTimeout(resolve, 1000))
    setIsRegenerating(false)
    // Trigger regeneration by updating timePeriod or stats
  }

  if (isLoading) {
    return (
      <Card className="border-0 shadow-md">
        <CardHeader>
          <CardTitle className="text-lg font-semibold flex items-center gap-2">
            <FileText className="w-5 h-5 text-purple-500" />
            AI Summary
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-center py-8">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-purple-500"></div>
          </div>
        </CardContent>
      </Card>
    )
  }

  if (!summary) {
    return (
      <Card className="border-0 shadow-md">
        <CardHeader>
          <CardTitle className="text-lg font-semibold flex items-center gap-2">
            <FileText className="w-5 h-5 text-purple-500" />
            AI Summary
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-gray-500 text-center py-4">
            No summary available. More data needed to generate insights.
          </p>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card className="border-0 shadow-md">
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle className="text-lg font-semibold flex items-center gap-2">
          <FileText className="w-5 h-5 text-purple-500" />
          AI Summary - {summary.period}
        </CardTitle>
        <Button
          variant="ghost"
          size="sm"
          onClick={handleRegenerate}
          disabled={isRegenerating}
          className="h-8"
        >
          <RefreshCw className={`w-4 h-4 mr-2 ${isRegenerating ? 'animate-spin' : ''}`} />
          Regenerate
        </Button>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Highlights */}
        {summary.highlights.length > 0 && (
          <div>
            <h4 className="text-sm font-semibold text-gray-900 mb-2 flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-purple-500" />
              Key Highlights
            </h4>
            <ul className="space-y-2">
              {(Array.isArray(summary.highlights) ? summary.highlights : []).map((highlight, index) => (
                <motion.li
                  key={index}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: index * 0.1 }}
                  className="flex items-start gap-2 text-sm text-gray-700"
                >
                  <CheckCircle className="w-4 h-4 text-success mt-0.5 flex-shrink-0" />
                  <span>{highlight}</span>
                </motion.li>
              ))}
            </ul>
          </div>
        )}

        {/* Metrics */}
        {summary.metrics.length > 0 && (
          <div>
            <h4 className="text-sm font-semibold text-gray-900 mb-2 flex items-center gap-2">
              <TrendingUp className="w-4 h-4 text-purple-500" />
              Performance Metrics
            </h4>
            <div className="grid grid-cols-2 gap-3">
              {(Array.isArray(summary.metrics) ? summary.metrics : []).map((metric, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ delay: index * 0.1 }}
                  className="p-3 bg-gradient-to-br from-purple-50 to-purple-100/50 rounded-lg border border-purple-200"
                >
                  <p className="text-xs text-gray-600 mb-1">{metric.label}</p>
                  <p className="text-lg font-bold text-purple-600">{metric.value}</p>
                  {metric.change && (
                    <p className="text-xs text-success mt-1">+{metric.change}% predicted</p>
                  )}
                </motion.div>
              ))}
            </div>
          </div>
        )}

        {/* Recommendations */}
        {summary.recommendations.length > 0 && (
          <div>
            <h4 className="text-sm font-semibold text-gray-900 mb-2 flex items-center gap-2">
              <AlertCircle className="w-4 h-4 text-amber-500" />
              AI Recommendations
            </h4>
            <ul className="space-y-2">
              {(Array.isArray(summary.recommendations) ? summary.recommendations : []).map((recommendation, index) => (
                <motion.li
                  key={index}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: index * 0.1 }}
                  className="flex items-start gap-2 text-sm text-gray-700 p-2 bg-amber-50 rounded-lg border border-amber-200"
                >
                  <span className="text-amber-600 font-semibold">{index + 1}.</span>
                  <span>{recommendation}</span>
                </motion.li>
              ))}
            </ul>
          </div>
        )}

        {/* Generated timestamp */}
        <div className="pt-2 border-t border-gray-200">
          <p className="text-xs text-gray-500">
            Generated at {summary.generatedAt.toLocaleTimeString('en-IN', {
              hour: '2-digit',
              minute: '2-digit',
            })}
          </p>
        </div>
      </CardContent>
    </Card>
  )
}
